//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectMedia.UI.TvShows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TvShowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TvShowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerfectMedia.UI.TvShows.TvShowResources", typeof(TvShowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors.
        /// </summary>
        public static string Actors {
            get {
                return ResourceManager.GetString("Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aired Date.
        /// </summary>
        public static string AiredDate {
            get {
                return ResourceManager.GetString("AiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change TV Show.
        /// </summary>
        public static string ChangeTvShow {
            get {
                return ResourceManager.GetString("ChangeTvShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directors.
        /// </summary>
        public static string Directors {
            get {
                return ResourceManager.GetString("Directors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Episode.
        /// </summary>
        public static string DisplayEpisode {
            get {
                return ResourceManager.GetString("DisplayEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Season.
        /// </summary>
        public static string DisplaySeason {
            get {
                return ResourceManager.GetString("DisplaySeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        public static string Episode {
            get {
                return ResourceManager.GetString("Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EpisodeNotFound {
            get {
                return ResourceManager.GetString("EpisodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find New Episodes.
        /// </summary>
        public static string FindNewEpisodes {
            get {
                return ResourceManager.GetString("FindNewEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Played.
        /// </summary>
        public static string LastPlayed {
            get {
                return ResourceManager.GetString("LastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPAA Rating.
        /// </summary>
        public static string MpaaRating {
            get {
                return ResourceManager.GetString("MpaaRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Count.
        /// </summary>
        public static string PlayCount {
            get {
                return ResourceManager.GetString("PlayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premiered Date.
        /// </summary>
        public static string PremieredDate {
            get {
                return ResourceManager.GetString("PremieredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime (in minutes).
        /// </summary>
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        public static string Specials {
            get {
                return ResourceManager.GetString("Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string Studio {
            get {
                return ResourceManager.GetString("Studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Show could not be located.
        /// </summary>
        public static string TvShowNotFound {
            get {
                return ResourceManager.GetString("TvShowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string UpdateAll {
            get {
                return ResourceManager.GetString("UpdateAll", resourceCulture);
            }
        }
    }
}
