using Ninject;
using PerfectMedia.FileInformation;
using PerfectMedia.Sources;
using PerfectMedia.TvShows;
using PerfectMedia.TvShows.Metadata;
using PerfectMedia.UI.Properties;
using PerfectMedia.UI.ViewModels.TvShows;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Ninject.Extensions.Conventions;
using System.Reflection;
using System.IO;

namespace PerfectMedia.UI
{
    public class ServiceLocator
    {
        private readonly IKernel _kernel;

        public TvShowManagerViewModel TvShowManagerViewModel
        {
            get
            {
                return _kernel.Get<TvShowManagerViewModel>();
            }
        }

        private IRestApiService TheTvDbRestApi
        {
            get
            {
                string theTvDbBaseUrl = ConfigurationManager.AppSettings["TheTvDbUrl"];
                return new RestApiService(theTvDbBaseUrl);
            }
        }

        public ServiceLocator()
        {
            _kernel = new StandardKernel();

            string currentAssemblyLocation = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            _kernel.Bind(config => config
                .FromAssembliesInPath(currentAssemblyLocation, assembly => {
                    // Only load assemblies from PerfectMedia, and don't include PerfectMedia.UI.vshost.exe generated by Visual Studio when debugging
                    string assemblyName = assembly.ManifestModule.Name;
                    return assemblyName.StartsWith("PerfectMedia") && !assemblyName.EndsWith("vshost.exe");
                })
                .SelectAllClasses()
                .BindAllInterfaces()
                .ConfigureFor<ThetvdbTvShowMetadataUpdater>(tvShowMetadataUpdater => tvShowMetadataUpdater.WithConstructorArgument(TheTvDbRestApi)));
        }
    }
}
