//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectMedia.UI.Music {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MusicResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MusicResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerfectMedia.UI.Music.MusicResources", typeof(MusicResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Formation.
        /// </summary>
        public static string DateOfFormation {
            get {
                return ResourceManager.GetString("DateOfFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceased Date.
        /// </summary>
        public static string DeceasedDate {
            get {
                return ResourceManager.GetString("DeceasedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disband Date.
        /// </summary>
        public static string DisbandDate {
            get {
                return ResourceManager.GetString("DisbandDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For a band).
        /// </summary>
        public static string ForBand {
            get {
                return ResourceManager.GetString("ForBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For a single artist).
        /// </summary>
        public static string ForSingleArtist {
            get {
                return ResourceManager.GetString("ForSingleArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments.
        /// </summary>
        public static string Instruments {
            get {
                return ResourceManager.GetString("Instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moods.
        /// </summary>
        public static string Moods {
            get {
                return ResourceManager.GetString("Moods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years Active.
        /// </summary>
        public static string YearsActive {
            get {
                return ResourceManager.GetString("YearsActive", resourceCulture);
            }
        }
    }
}
